version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - wget -q https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
      - unzip terraform_0.12.3_linux_amd64.zip -d temp
      - mv temp/terraform /bin/
      - npm i -g yarn
      - yarn install
  build:
    commands:
      - yarn start
artifacts:
  files:
    - 'build/**/*'
