version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - wget -q https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
      - unzip terraform_0.12.3_linux_amd64.zip
      - rm -rf terraform_0.12.3_linux_amd64.zip
      - mv terraform /bin
      - npm i -g yarn
  build:
    commands:
      - yarn start
artifacts:
  files:
    - 'build/**/*'
