on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      # source checkout
      - uses: actions/checkout@master

      # install nodejs
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      # yarn cache
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(~/.cache/yarn)"

      # - uses: actions/cache@v1
      #   id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # install and build
      - name: install and build
        run: |
          yarn install
          yarn build

      # zip folders
      - name: zip folder
        working-directory: build
        run: |
          zip -r -j m006 m006/**

      - uses: docker://amazon/aws-cli
        with:
          args: lambda update-function-code --function-name PocketCards_CloudFront_Invalidation --zip fileb://./build/m006.zip

  Slack:
    runs-on: ubuntu-latest

    steps:
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: build
          SLACK_TITLE: Automation Build
          SLACK_COLOR: '#43a047'
          SLACK_MESSAGE: ${{ github.repository }} Build Success
          SLACK_USERNAME: ${{ github.repository }}
